# Default values for my-helm-chart.
# This is a YAML-formatted file.
# Declare any variables to be passed into your templates.

replicaCount: 1

image:
  repository: nginx
  tag: "latest"
  pullPolicy: IfNotPresent

service:
  name: default-service
  type: ClusterIP
  port: 80

ingress:
  enabled: false
  name: ""
  path: /
  hosts:
    - host: chart-example.local
      paths: []
  tls: []
